# Generated by Django 2.1.2 on 2019-01-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_course_classes_held'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='being_held',
            field=models.BooleanField(default=False),
        ),
    ]
